name: Remote SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 3.110.29.220
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd devops/server
            git pull
            npm install
            npm run build
            pm2 reload nestjs-app || pm2 start dist/main.js --name "nestjs-app"
            pm2 save
