name: Remote SSH Command

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Execute remote SSH command
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 3.110.29.220
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd devops/server
            git pull
            npm install

            pm2 start app.js
            
